// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhwefvwypsfvreihswbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZod2Vmdnd5cHNmdnJlaWhzd2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTc5NzQsImV4cCI6MjA1ODM5Mzk3NH0.9323vvDrvq0Ut4Il0hULcRCplf5ortOsRF67NBb88ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);